using Gob3AQ.VARMAP.Types;
using System;
using UnityEngine;

namespace Gob3AQ.ResourceSoundsAtlas
{
    public static class ResourceSoundsAtlasClass
    {
        public static ref readonly SoundConfig GetSoundConfig(GameSound sound)
        {
            if ((uint)sound < (uint)GameSound.SOUND_TOTAL)
            {
                return ref _SoundConfig[(int)sound];
            }
            else
            {
                Debug.LogError($"Trying to get SoundConfig for invalid sound {sound}");
                return ref SoundConfig.EMPTY;
            }
        }


        private static readonly SoundConfig[] _SoundConfig = new SoundConfig[(int)GameSound.SOUND_TOTAL]
        {
            /* > ATG 1 START < */
            new(SoundEffect.EFFECT_NONE,"MUSIC_GARDEN"), /* MUSIC_GARDEN */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_OBSERVE_ITEM_EXTRAPERLO_INVITATION_DETAIL_SPANISH"), /* SOUND_OBSERVE_ITEM_EXTRAPERLO_INVITATION_DETAIL */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_OBSERVE_ITEM_SHOELACE_SPANISH"), /* SOUND_OBSERVE_ITEM_SHOELACE */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FART_1"), /* SOUND_FART_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_POOR_MAN_BCKG_1"), /* SOUND_POOR_MAN_BCKG_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_POOR_MAN_BCKG_2"), /* SOUND_POOR_MAN_BCKG_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_POOR_MAN_BCKG_3"), /* SOUND_POOR_MAN_BCKG_3 */ 
            new(SoundEffect.EFFECT_NONE,"MUSIC_PHARMACY"), /* MUSIC_PHARMACY */ 
            new(SoundEffect.EFFECT_NONE,"MUSIC_SOUTH_NEIGH"), /* MUSIC_SOUTH_NEIGH */ 
            new(SoundEffect.EFFECT_NONE,"MUSIC_MANYO"), /* MUSIC_MANYO */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_AMBIENCE_MANYO_NIGHT"), /* SOUND_AMBIENCE_MANYO_NIGHT */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_AMBIENCE_CITY_DAY"), /* SOUND_AMBIENCE_CITY_DAY */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_AMBIENCE_CITY_NIGHT"), /* SOUND_AMBIENCE_CITY_NIGHT */ 
            new(SoundEffect.EFFECT_NONE,"MUSIC_INN"), /* MUSIC_INN */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_INTRO_1_SPANISH"), /* SOUND_FIK_INTRO_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_INTRO_2_SPANISH"), /* SOUND_FIK_INTRO_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_0_0_SPANISH"), /* SOUND_FIK_1_OP_0_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_0_1_SPANISH"), /* SOUND_FIK_1_OP_0_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_1_0_SPANISH"), /* SOUND_FIK_1_OP_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_1_1_SPANISH"), /* SOUND_FIK_1_OP_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_1_2_SPANISH"), /* SOUND_FIK_1_OP_1_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_1_3_SPANISH"), /* SOUND_FIK_1_OP_1_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_2_0_SPANISH"), /* SOUND_FIK_1_OP_2_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_2_1_SPANISH"), /* SOUND_FIK_1_OP_2_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_1_OP_3_0_SPANISH"), /* SOUND_FIK_1_OP_3_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_0_0_SPANISH"), /* SOUND_FIK_2_OP_0_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_0_1_SPANISH"), /* SOUND_FIK_2_OP_0_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_1_0_SPANISH"), /* SOUND_FIK_2_OP_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_1_1_SPANISH"), /* SOUND_FIK_2_OP_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_2_0_SPANISH"), /* SOUND_FIK_2_OP_2_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_2_1_SPANISH"), /* SOUND_FIK_2_OP_2_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_3_0_SPANISH"), /* SOUND_FIK_2_OP_3_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_2_OP_3_1_SPANISH"), /* SOUND_FIK_2_OP_3_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_FIK_NOT_CROSS_SPANISH"), /* SOUND_FIK_NOT_CROSS */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_MAINCHAR_NONSENSE_SPANISH"), /* SOUND_MAINCHAR_NONSENSE */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_MAINCHAR_NONSENSE_OBSERVE_SPANISH"), /* SOUND_MAINCHAR_NONSENSE_OBSERVE */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_MAINCHAR_NONSENSE_TALK_SPANISH"), /* SOUND_MAINCHAR_NONSENSE_TALK */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_PHRASE_DIALOG_MANYO_BCKG_CROWD_1_SPANISH"), /* SOUND_PHRASE_DIALOG_MANYO_BCKG_CROWD_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_PHRASE_DIALOG_MANYO_BCKG_CROWD_2_SPANISH"), /* SOUND_PHRASE_DIALOG_MANYO_BCKG_CROWD_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_PHRASE_DIALOG_MANYO_BCKG_CROWD_3_SPANISH"), /* SOUND_PHRASE_DIALOG_MANYO_BCKG_CROWD_3 */ 
            new(SoundEffect.EFFECT_NONE,"MUSIC_EXTRAPERLO"), /* MUSIC_EXTRAPERLO */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_AMBIENCE_WATER_FLOW"), /* SOUND_AMBIENCE_WATER_FLOW */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_AMBIENCE_INSIDE_PUB"), /* SOUND_AMBIENCE_INSIDE_PUB */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_AMBIENCE_OUTSIDE_PUB"), /* SOUND_AMBIENCE_OUTSIDE_PUB */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_GERMAN_INTRO"), /* SOUND_GERMAN_INTRO */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_GERMAN_1_OP_0_0_SPANISH"), /* SOUND_GERMAN_1_OP_0_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_GERMAN_1_OP_0_1_SPANISH"), /* SOUND_GERMAN_1_OP_0_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_GERMAN_1_OP_1_0_SPANISH"), /* SOUND_GERMAN_1_OP_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_GERMAN_1_OP_1_1_SPANISH"), /* SOUND_GERMAN_1_OP_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_GERMAN_1_OP_1_2_SPANISH"), /* SOUND_GERMAN_1_OP_1_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_GERMAN_SHOUTS_COCAI"), /* SOUND_GERMAN_SHOUTS_COCAI */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_INTRO_1_0_SPANISH"), /* SOUND_WAITER_INTRO_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_INTRO_1_1_SPANISH"), /* SOUND_WAITER_INTRO_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_INTRO_1_2_SPANISH"), /* SOUND_WAITER_INTRO_1_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_INTRO_1_3_SPANISH"), /* SOUND_WAITER_INTRO_1_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_INTRO_2_0"), /* SOUND_WAITER_INTRO_2_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_USE_INVITATION_1_SPANISH"), /* SOUND_WAITER_USE_INVITATION_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_USE_INVITATION_2_SPANISH"), /* SOUND_WAITER_USE_INVITATION_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_WAITER_USE_INVITATION_3_SPANISH"), /* SOUND_WAITER_USE_INVITATION_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_UNKNOWN_WOMEN_INTRO_1_0_SPANISH"), /* SOUND_UNKNOWN_WOMEN_INTRO_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_UNKNOWN_WOMEN_INTRO_1_1_SPANISH"), /* SOUND_UNKNOWN_WOMEN_INTRO_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_TAKE_UNKNOWN_WOMEN_SPANISH"), /* SOUND_TAKE_UNKNOWN_WOMEN */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_OBSERVE_EXTRAPERLO_ARTURO_SPANISH"), /* SOUND_OBSERVE_EXTRAPERLO_ARTURO */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_INTRO_1_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_INTRO_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_0_0_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_0_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_0_1_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_0_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_0_2_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_0_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_0_3_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_0_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_1_0_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_1_1_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_1_2_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_1_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_1_3_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_1_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_1_4_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_1_4 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_0_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_1_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_2_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_3_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_4_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_4 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_5_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_5 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_6_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_6 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_ARTURO_EXTRAPERLO_OP_2_7_SPANISH"), /* SOUND_ARTURO_EXTRAPERLO_OP_2_7 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARD_PLACE_1"), /* SOUND_CARD_PLACE_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARD_PLACE_2"), /* SOUND_CARD_PLACE_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARD_PLACE_3"), /* SOUND_CARD_PLACE_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARD_TAKEBACK"), /* SOUND_CARD_TAKEBACK */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_MAINCHAR_TAUNT_1_SPANISH"), /* SOUND_CARDS1_MAINCHAR_TAUNT1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_MAINCHAR_TAUNT_2_SPANISH"), /* SOUND_CARDS1_MAINCHAR_TAUNT2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_MAINCHAR_TAUNT_3_SPANISH"), /* SOUND_CARDS1_MAINCHAR_TAUNT3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_MAINCHAR_TAUNT_4_SPANISH"), /* SOUND_CARDS1_MAINCHAR_TAUNT4 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_MAINCHAR_TAUNT_5_SPANISH"), /* SOUND_CARDS1_MAINCHAR_TAUNT5 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_TAUNT_ARTURO_1_SPANISH"), /* SOUND_CARDS1_TAUNT_ARTURO_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_TAUNT_ARTURO_2_SPANISH"), /* SOUND_CARDS1_TAUNT_ARTURO_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_TAUNT_ARTURO_3_SPANISH"), /* SOUND_CARDS1_TAUNT_ARTURO_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_TAUNT_ARTURO_4_SPANISH"), /* SOUND_CARDS1_TAUNT_ARTURO_4 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_TAUNT_ARTURO_5_SPANISH"), /* SOUND_CARDS1_TAUNT_ARTURO_5 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_TAUNT_ARTURO_6_SPANISH"), /* SOUND_CARDS1_TAUNT_ARTURO_6 */ 
            new(SoundEffect.EFFECT_NONE,"MUSIC_CARDS"), /* MUSIC_CARDS */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_MAINCHAR_TAUNT_WIN_SPANISH"), /* SOUND_CARDS1_MAINCHAR_WIN */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CARDS1_TAUNT_ARTURO_WIN_SPANISH"), /* SOUND_CARDS1_TAUNT_ARTURO_WIN */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP0_0_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP0_1_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP0_2_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_1_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP0_3_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_1_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP0_4_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_1_4 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP1_0_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_2_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP1_1_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_2_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_0_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_1_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_2_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_4 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_3_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_5 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_4_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_6 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_5_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_7 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_6_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_8 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_OP2_7_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_OPTION_3_9 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_CLOWN_INTRO_SPANISH"), /* SOUND_PHRASE_DIALOG_CLOWN_EXTRAPERLO_INTRO */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_OP_0_0_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_OPTION_0_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_OP_0_1_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_OPTION_0_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_OP_0_2_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_OPTION_0_2 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_OP_0_3_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_OPTION_0_3 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_OP_1_0_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_OPTION_1_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_OP_1_1_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_OPTION_1_1 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_INTRO1_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_INTRO_0 */ 
            new(SoundEffect.EFFECT_NONE,"SOUND_SILVANA_INTRO2_SPANISH"), /* SOUND_PHRASE_DIALOG_SILVANA_EXTRAPERLO_INTRO_1 */ 
            new(SoundEffect.EFFECT_NONE,""), /* SOUND_LAST */ 
            /* > ATG 1 END < */
        };
    }
}