using Gob3AQ.VARMAP.Types;
using System;
using UnityEngine;

namespace Gob3AQ.ResourceSpritesAtlas
{
    public static class ResourceSpritesAtlasClass
    {
        public static ref readonly SpriteConfig GetSpriteConfig(GameSprite sprite)
        {
            if ((uint)sprite < (uint)GameSprite.SPRITE_TOTAL)
            {
                return ref _SpriteConfig[(int)sprite];
            }
            else
            {
                Debug.LogError($"Trying to get SpriteConfig for invalid sprite {sprite}");
                return ref SpriteConfig.EMPTY;
            }
        }


        private static readonly SpriteConfig[] _SpriteConfig = new SpriteConfig[(int)GameSprite.SPRITE_TOTAL]
        {
            /* > ATG 1 START < */
            new("SPRITE_ATLAS_UI_0[SPRITE_BLANK]"), /* SPRITE_BLANK */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_CURSOR_NORMAL]"), /* SPRITE_CURSOR_NORMAL */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_CURSOR_USING]"), /* SPRITE_CURSOR_USING */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_CURSOR_DRAG]"), /* SPRITE_CURSOR_DRAG */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_INVENTORY]"), /* SPRITE_INVENTORY */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_ACTION_TAKE]"), /* SPRITE_UI_TAKE */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_ACTION_TALK]"), /* SPRITE_UI_TALK */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_ACTION_OBSERVE]"), /* SPRITE_UI_OBSERVE */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_MOUSE_MOVE]"), /* SPRITE_UI_MOUSE_MOVE */ 
            new("SPRITE_ATLAS_UI_0[SPRITE_CURSOR_DOOR]"), /* SPRITE_UI_CURSOR_DOOR */ 
            new("SPRITE_ATLAS_HIVE1_0[BACKGROUND_HIVE1_ROOM1]"), /* BACKGROUND_HIVE1_ROOM1 */ 
            new("SPRITE_ATLAS_HIVE1_0[SPRITE_HIVE1_CHEST_CLOSED]"), /* SPRITE_ITEM_CHEST_CLOSED */ 
            new("SPRITE_ATLAS_HIVE1_0[SPRITE_HIVE1_CHEST_OPENED]"), /* SPRITE_ITEM_CHEST_OPENED */ 
            new("SPRITE_ATLAS_HIVE1_0[SPRITE_HIVE1_CHEST_CARDS]"), /* SPRITE_ITEM_CARDS */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_PICKABLE_CARDS]"), /* SPRITE_ITEM_CARDS_PICKABLE */ 
            new("SPRITE_ATLAS_HIVE1_0[SPRITE_HIVE1_BED_LAYER]"), /* SPRITE_ITEM_DECO_BED_LAYER */ 
            new("SPRITE_ATLAS_HIVE1_0[SPRITE_HIVE1_WARDROBE_OPENED]"), /* SPRITE_ITEM_WARDROBE_OPENED */ 
            new("SPRITE_ATLAS_HIVE1_1[BACKGROUND_HIVE1_CORRIDOR1]"), /* BACKGROUND_HIVE1_CORRIDOR1 */ 
            new("SPRITE_ATLAS_HIVE1_1[SPRITE_HIVE1_REME_IDLE]"), /* SPRITE_NPC_REME_IDLE */ 
            new("SPRITE_ATLAS_HIVE1_2[BACKGROUND_HIVE1_HALL1]"), /* BACKGROUND_HIVE1_HALL1 */ 
            new("SPRITE_ATLAS_HIVE1_3[BACKGROUND_HIVE1_WC]"), /* BACKGROUND_HIVE1_WC */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_MEMENTO_JOB]"), /* SPRITE_MEMENTO_JOB */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_PICKABLE_SOAP]"), /* SPRITE_PICKABLE_SOAP */ 
            new("SPRITE_ATLAS_HIVE1_4[BACKGROUND_HIVE1_CORRIDOR1_NIGHT]"), /* BACKGROUND_HIVE1_CORRIDOR1_N */ 
            new("SPRITE_ATLAS_HIVE1_5[BACKGROUND_HIVE1_HALL1_NIGHT]"), /* BACKGROUND_HIVE1_HALL1_N */ 
            new("SPRITE_ATLAS_HIVE1_6[BACKGROUND_HIVE1_WC_NIGHT]"), /* BACKGROUND_HIVE1_WC_N */ 
            new("SPRITE_ATLAS_CITY1_1[BACKGROUND_CITY1_STREET1]"), /* BACKGROUND_CITY1_STREET1 */ 
            new("SPRITE_ATLAS_CITY1_2[BACKGROUND_CITY1_STREET1_NIGHT]"), /* BACKGROUND_CITY1_STREET1_N */ 
            new("SPRITE_ATLAS_CITY2_1[BACKGROUND_CITY1_STREET2]"), /* BACKGROUND_CITY1_STREET2 */ 
            new("SPRITE_ATLAS_CITY2_2[BACKGROUND_CITY1_STREET2_NIGHT]"), /* BACKGROUND_CITY1_STREET2_N */ 
            new("SPRITE_ATLAS_PHARMACY1_1[BACKGROUND_PHARMACY1]"), /* BACKGROUND_PHARMACY1 */ 
            new("SPRITE_ATLAS_PHARMACY1_1[SPRITE_PHARMACY_QUEUE_1]"), /* SPRITE_NPC_PHARMACY_QUEUE */ 
            new("SPRITE_ATLAS_PHARMACY1_1[SPRITE_PHARMACY_OWNER]"), /* SPRITE_NPC_PHARMACY_OWNER */ 
            new("SPRITE_ATLAS_MANYO_0[BACKGROUND_CITY1_MANYO]"), /* BACKGROUND_CITY1_MANYO */ 
            new("SPRITE_ATLAS_MANYO_1[BACKGROUND_CITY1_MANYO_NIGHT]"), /* BACKGROUND_CITY1_MANYO_NIGHT */ 
            new("SPRITE_ATLAS_MANYO_0[SPRITE_CITY1_MANYO_UMBRELLA]"), /* SPRITE_CITY1_MANYO_UMBRELLA */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_PICKABLE_UMBRELLA]"), /* SPRITE_PICKABLE_UMBRELLA */ 
            new("SPRITE_ATLAS_MANYO_0[SPRITE_MANYO_OWNER]"), /* SPRITE_MANYO_OWNER */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_MEMENTO_RECIPE]"), /* SPRITE_MEMENTO_RECIPE */ 
            new("SPRITE_ATLAS_HIVE1_6[SPRITE_HIVE1_POOR_MAN_STEADY]"), /* SPRITE_HIVE1_POOR_MAN_STEADY */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_MEMENTO_JOB]"), /* SPRITE_MEMENTO_POOR_MAN_WC */ 
            new("SPRITE_ATLAS_HIVE1_6[SPRITE_HIVE1_ROACH_HEAD]"), /* SPRITE_HIVE1_ROACH_HEAD */ 
            new("SPRITE_ATLAS_HIVE1_7[BACKGROUND_HIVE1_BACKALLEY]"), /* BACKGROUND_BACKALLEY */ 
            new("SPRITE_ATLAS_HIVE1_8[BACKGROUND_HIVE1_BACKALLEY_NIGHT]"), /* BACKGROUND_BACKALLEY_NIGHT */ 
            new("SPRITE_ATLAS_HIVE1_2[SPRITE_HIVE1_SHOELACE]"), /* SPRITE_HIVE1_SHOELACE */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_PICKABLE_SHOELACE]"), /* SPRITE_SHOELACE_PICKABLE */ 
            new("SPRITE_ATLAS_HIVE1_7[SPRITE_HIVE1_VALVE_BOX_OPENED]"), /* SPRITE_HIVE1_VALVE_BOX_OPENED */ 
            new("SPRITE_ATLAS_HIVE1_5[SPRITE_ARTURO_STANDING]"), /* SPRITE_ARTURO_STANDING */ 
            new("SPRITE_ATLAS_PICKABLE_0[SPRITE_PICKABLE_EXTRAPERLO]"), /* SPRITE_PICKABLE_EXTRAPERLO */ 
            new("SPRITE_ATLAS_PHARMACY1_1[SPRITE_PHARMACY_INKWELL_NORMAL]"), /* SPRITE_PHARMACY_INKWELL_NORMAL */ 
            new("SPRITE_ATLAS_PHARMACY1_1[SPRITE_PHARMACY_INKWELL_WASTED]"), /* SPRITE_PHARMACY_INKWELL_WASTED */ 
            new("SPRITE_LAST"), /* SPRITE_LAST */ 
            /* > ATG 1 END < */
        };


    }
}