using Gob3AQ.VARMAP.Types;
using System;
using UnityEngine;

namespace Gob3AQ.ResourceSpritesAtlas
{
    public static class ResourceSpritesAtlasClass
    {
        public static ref readonly SpriteConfig GetSpriteConfig(GameSprite sprite)
        {
            if ((uint)sprite < (uint)GameSprite.SPRITE_TOTAL)
            {
                return ref _SpriteConfig[(int)sprite];
            }
            else
            {
                Debug.LogError($"Trying to get SpriteConfig for invalid sprite {sprite}");
                return ref SpriteConfig.EMPTY;
            }
        }


        private static readonly SpriteConfig[] _SpriteConfig = new SpriteConfig[(int)GameSprite.SPRITE_TOTAL]
        {
            /* > ATG 1 START < */
            new("SPRITE_BLANK", "SPRITE_ATLAS_UI_0"), /* SPRITE_BLANK */ 
            new("SPRITE_CURSOR_NORMAL", "SPRITE_ATLAS_UI_0"), /* SPRITE_CURSOR_NORMAL */ 
            new("SPRITE_CURSOR_USING", "SPRITE_ATLAS_UI_0"), /* SPRITE_CURSOR_USING */ 
            new("SPRITE_CURSOR_DRAG", "SPRITE_ATLAS_UI_0"), /* SPRITE_CURSOR_DRAG */ 
            new("SPRITE_INVENTORY", "SPRITE_ATLAS_UI_0"), /* SPRITE_INVENTORY */ 
            new("SPRITE_ACTION_TAKE", "SPRITE_ATLAS_UI_0"), /* SPRITE_UI_TAKE */ 
            new("SPRITE_ACTION_TALK", "SPRITE_ATLAS_UI_0"), /* SPRITE_UI_TALK */ 
            new("SPRITE_ACTION_OBSERVE", "SPRITE_ATLAS_UI_0"), /* SPRITE_UI_OBSERVE */ 
            new("SPRITE_MOUSE_MOVE", "SPRITE_ATLAS_UI_0"), /* SPRITE_UI_MOUSE_MOVE */ 
            new("SPRITE_CURSOR_DOOR", "SPRITE_ATLAS_UI_0"), /* SPRITE_UI_CURSOR_DOOR */ 
            new("BACKGROUND_HIVE1_ROOM1", "SPRITE_ATLAS_HIVE1_0"), /* BACKGROUND_HIVE1_ROOM1 */ 
            new("SPRITE_HIVE1_CHEST_CLOSED", "SPRITE_ATLAS_HIVE1_0"), /* SPRITE_ITEM_CHEST_CLOSED */ 
            new("SPRITE_HIVE1_CHEST_OPENED", "SPRITE_ATLAS_HIVE1_0"), /* SPRITE_ITEM_CHEST_OPENED */ 
            new("SPRITE_HIVE1_CHEST_CARDS", "SPRITE_ATLAS_HIVE1_0"), /* SPRITE_ITEM_CARDS */ 
            new("SPRITE_PICKABLE_CARDS", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_ITEM_CARDS_PICKABLE */ 
            new("SPRITE_HIVE1_BED_LAYER", "SPRITE_ATLAS_HIVE1_0"), /* SPRITE_ITEM_DECO_BED_LAYER */ 
            new("SPRITE_HIVE1_WARDROBE_OPENED", "SPRITE_ATLAS_HIVE1_0"), /* SPRITE_ITEM_WARDROBE_OPENED */ 
            new("BACKGROUND_HIVE1_CORRIDOR1", "SPRITE_ATLAS_HIVE1_1"), /* BACKGROUND_HIVE1_CORRIDOR1 */ 
            new("SPRITE_HIVE1_REME_IDLE", "SPRITE_ATLAS_HIVE1_1"), /* SPRITE_NPC_REME_IDLE */ 
            new("BACKGROUND_HIVE1_HALL1", "SPRITE_ATLAS_HIVE1_2"), /* BACKGROUND_HIVE1_HALL1 */ 
            new("BACKGROUND_HIVE1_WC", "SPRITE_ATLAS_HIVE1_3"), /* BACKGROUND_HIVE1_WC */ 
            new("SPRITE_MEMENTO_JOB", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_MEMENTO_JOB */ 
            new("SPRITE_PICKABLE_SOAP", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_PICKABLE_SOAP */ 
            new("BACKGROUND_HIVE1_CORRIDOR1_NIGHT", "SPRITE_ATLAS_HIVE1_4"), /* BACKGROUND_HIVE1_CORRIDOR1_N */ 
            new("BACKGROUND_HIVE1_HALL1_NIGHT", "SPRITE_ATLAS_HIVE1_5"), /* BACKGROUND_HIVE1_HALL1_N */ 
            new("BACKGROUND_HIVE1_WC_NIGHT", "SPRITE_ATLAS_HIVE1_6"), /* BACKGROUND_HIVE1_WC_N */ 
            new("BACKGROUND_CITY1_STREET1", "SPRITE_ATLAS_CITY1_1"), /* BACKGROUND_CITY1_STREET1 */ 
            new("BACKGROUND_CITY1_STREET1_NIGHT", "SPRITE_ATLAS_CITY1_2"), /* BACKGROUND_CITY1_STREET1_N */ 
            new("BACKGROUND_CITY1_STREET2", "SPRITE_ATLAS_CITY2_1"), /* BACKGROUND_CITY1_STREET2 */ 
            new("BACKGROUND_CITY1_STREET2_NIGHT", "SPRITE_ATLAS_CITY2_2"), /* BACKGROUND_CITY1_STREET2_N */ 
            new("BACKGROUND_PHARMACY1", "SPRITE_ATLAS_PHARMACY1_1"), /* BACKGROUND_PHARMACY1 */ 
            new("SPRITE_PHARMACY_QUEUE_1", "SPRITE_ATLAS_PHARMACY1_1"), /* SPRITE_NPC_PHARMACY_QUEUE */ 
            new("SPRITE_PHARMACY_OWNER", "SPRITE_ATLAS_PHARMACY1_1"), /* SPRITE_NPC_PHARMACY_OWNER */ 
            new("BACKGROUND_CITY1_MANYO", "SPRITE_ATLAS_MANYO_0"), /* BACKGROUND_CITY1_MANYO */ 
            new("BACKGROUND_CITY1_MANYO_NIGHT", "SPRITE_ATLAS_MANYO_1"), /* BACKGROUND_CITY1_MANYO_NIGHT */ 
            new("SPRITE_CITY1_MANYO_UMBRELLA", "SPRITE_ATLAS_MANYO_0"), /* SPRITE_CITY1_MANYO_UMBRELLA */ 
            new("SPRITE_PICKABLE_UMBRELLA", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_PICKABLE_UMBRELLA */ 
            new("SPRITE_MANYO_OWNER", "SPRITE_ATLAS_MANYO_0"), /* SPRITE_MANYO_OWNER */ 
            new("SPRITE_MEMENTO_RECIPE", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_MEMENTO_RECIPE */ 
            new("SPRITE_HIVE1_POOR_MAN_STEADY", "SPRITE_ATLAS_HIVE1_6"), /* SPRITE_HIVE1_POOR_MAN_STEADY */ 
            new("SPRITE_MEMENTO_JOB", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_MEMENTO_POOR_MAN_WC */ 
            new("SPRITE_HIVE1_ROACH_HEAD", "SPRITE_ATLAS_HIVE1_6"), /* SPRITE_HIVE1_ROACH_HEAD */ 
            new("BACKGROUND_HIVE1_BACKALLEY", "SPRITE_ATLAS_HIVE1_7"), /* BACKGROUND_BACKALLEY */ 
            new("BACKGROUND_HIVE1_BACKALLEY_NIGHT", "SPRITE_ATLAS_HIVE1_8"), /* BACKGROUND_BACKALLEY_NIGHT */ 
            new("SPRITE_HIVE1_SHOELACE", "SPRITE_ATLAS_HIVE1_2"), /* SPRITE_HIVE1_SHOELACE */ 
            new("SPRITE_PICKABLE_SHOELACE", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_SHOELACE_PICKABLE */ 
            new("SPRITE_HIVE1_VALVE_BOX_OPENED", "SPRITE_ATLAS_HIVE1_7"), /* SPRITE_HIVE1_VALVE_BOX_OPENED */ 
            new("SPRITE_ARTURO_STANDING", "SPRITE_ATLAS_HIVE1_5"), /* SPRITE_ARTURO_STANDING */ 
            new("SPRITE_PICKABLE_EXTRAPERLO", "SPRITE_ATLAS_PICKABLE_0"), /* SPRITE_PICKABLE_EXTRAPERLO */ 
            new("SPRITE_PHARMACY_INKWELL_NORMAL", "SPRITE_ATLAS_PHARMACY1_1"), /* SPRITE_PHARMACY_INKWELL_NORMAL */ 
            new("SPRITE_PHARMACY_INKWELL_WASTED", "SPRITE_ATLAS_PHARMACY1_1"), /* SPRITE_PHARMACY_INKWELL_WASTED */ 
            new("BACKGROUND_CITY1_SOUTH_STREET_1", "SPRITE_ATLAS_CITY3_1"), /* BACKGROUND_CITY1_SOUTH_STREET_1 */ 
            new("BACKGROUND_CITY1_SOUTH_STREET_1_NIGHT", "SPRITE_ATLAS_CITY3_2"), /* BACKGROUND_CITY1_SOUTH_STREET_1_NIGHT */ 
            new("BACKGROUND_CITY1_SOUTH_STREET_2", "SPRITE_ATLAS_CITY4_1"), /* BACKGROUND_CITY1_SOUTH_STREET_2 */ 
            new("BACKGROUND_CITY1_SOUTH_STREET_2_NIGHT", "SPRITE_ATLAS_CITY4_2"), /* BACKGROUND_CITY1_SOUTH_STREET_2_NIGHT */ 
            new("BACKGROUND_CITY1_EXTRAPERLO", "SPRITE_ATLAS_EXTRAPERLO1"), /* BACKGROUND_CITY1_EXTRAPERLO */ 
            new("SPRITE_EXTRAPERLO_BAR_FOREGROUND", "SPRITE_ATLAS_EXTRAPERLO1"), /* SPRITE_EXTRAPERLO_BAR_FOREGROUND */ 
            new("SPRITE_FIK_STANDING", "SPRITE_ATLAS_FIK_1"), /* SPRITE_FIK_STANDING */ 
            new("SPRITE_MAINCHAR_STEADY", "SPRITE_ATLAS_MAINCHAR_1"), /* SPRITE_MAINCHAR_STEADY */ 
            new("SPRITE_EXTRAPERLO_DOOR_OPENED", "SPRITE_ATLAS_CITY4_2"), /* SPRITE_EXTRAPERLO_DOOR_OPENED */ 
            new("SPRITE_FOREGROUND_EXTRAPERLO_WALL", "SPRITE_ATLAS_CITY4_2"), /* SPRITE_FOREGROUND_EXTRAPERLO_WALL */ 
            new("SPRITE_WATER_FLOW_BACKALLEY", "SPRITE_ATLAS_HIVE1_7"), /* SPRITE_WATER_FLOW_BACKALLEY */ 
            new("SPRITE_WATER_FLOW_BACKALLEY_NIGHT", "SPRITE_ATLAS_HIVE1_8"), /* SPRITE_WATER_FLOW_BACKALLEY_NIGHT */ 
            new("SPRITE_GERMAN_WAITING", "SPRITE_ATLAS_GERMAN_1"), /* SPRITE_GERMAN_WAITING */ 
            new("SPRITE_WAITER_STEADY", "SPRITE_ATLAS_WAITER_1"), /* SPRITE_WAITER_STEADY */ 
            new("BACKGROUND_CITY1_EXTRAPERLO2", "SPRITE_ATLAS_EXTRAPERLO2"), /* BACKGROUND_CITY1_EXTRAPERLO2 */ 
            new("SPRITE_UNKNOWN_WOMEN_STEADY", "SPRITE_ATLAS_UNKNOWN_WOMEN_1"), /* SPRITE_UNKNOWN_WOMEN_STEADY */ 
            new("SPRITE_LAST", ""), /* SPRITE_LAST */ 
            /* > ATG 1 END < */
        };


    }
}