namespace Gob3AQ.VARMAP.Enum
{
    public enum VARMAP_Variable_ID
    {
        /* > ATG 1 START < */
        VARMAP_ID_GAME_OPTIONS,
        VARMAP_ID_ELAPSED_TIME_MS,
        VARMAP_ID_ACTUAL_ROOM,
        VARMAP_ID_EVENTS_OCCURRED,
        VARMAP_ID_UNLOCKED_MEMENTO,
        VARMAP_ID_PICKABLE_ITEM_OWNER,
        VARMAP_ID_PLAYER_ACTUAL_WAYPOINT,
        VARMAP_ID_CAMERA_DISPOSITION,
        VARMAP_ID_GAMESTATUS,
        VARMAP_ID_PRESSED_KEYS,
        VARMAP_ID_MOUSE_PROPERTIES,
        VARMAP_ID_PLAYER_SELECTED,
        VARMAP_ID_PICKABLE_ITEM_CHOSEN,
        VARMAP_ID_ITEM_HOVER,
        VARMAP_ID_USER_INPUT_INTERACTION,
        VARMAP_ID_EVENTS_BEING_PROCESSED,
        VARMAP_ID_LAST_VARMAP_VAL,
        VARMAP_ID_TOTAL
        /* > ATG 1 END < */
    }

    
}
