

namespace Gob3AQ.VARMAP.Types
{
    public enum GameSprite
    {
        /* > ATG 1 START < */
        SPRITE_NONE = -1, 
        SPRITE_CURSOR_NORMAL, 
        SPRITE_CURSOR_USING, 
        SPRITE_CURSOR_DRAG, 
        SPRITE_INVENTORY, 
        SPRITE_UI_TAKE, 
        SPRITE_UI_TALK, 
        SPRITE_UI_OBSERVE, 
        SPRITE_UI_MOUSE_MOVE, 
        BACKGROUND_ROOM1, 
        SPRITE_ROOM1_VICTIM, 
        SPRITE_ROOM1_WITNESS1, 
        SPRITE_ROOM1_WITNESS2, 
        SPRITE_ROOM1_WITNESS3, 
        SPRITE_ROOM1_DECO_TABLE, 
        SPRITE_MEMENTO_CHASE, 
        SPRITE_UI_CURSOR_DOOR, 
        BACKGROUND_ROOM1_KITCHEN, 
        SPRITE_ROOM1_KITCHEN_BASIN, 
        SPRITE_ROOM1_SPOON, 
        SPRITE_ROOM1_DRAWER, 
        SPRITE_ROOM1_WINDOW_CLOSED, 
        SPRITE_ROOM1_JAM, 
        SPRITE_PICKABLE_SPOON, 
        SPRITE_ROOM1_POISON_REMAIN, 
        SPRITE_PICKABLE_SPOON_POISON, 
        SPRITE_PICKABLE_OLD_HOUSE_KEY, 
        SPRITE_ROOM1_TROWEL, 
        SPRITE_PICKABLE_TROWEL, 
        SPRITE_ROOM1_WINDOW_OPENED_1, 
        SPRITE_ROOM1_WINDOW_OPENED_2, 
        SPRITE_LAST, 
        
        SPRITE_TOTAL
        /* > ATG 1 END < */
    }
}
