

namespace Gob3AQ.VARMAP.Types
{
    public enum GameSprite
    {
        /* > ATG 1 START < */
        SPRITE_NONE = -1, 
        SPRITE_BLANK, 
        SPRITE_CURSOR_NORMAL, 
        SPRITE_CURSOR_USING, 
        SPRITE_CURSOR_DRAG, 
        SPRITE_INVENTORY, 
        SPRITE_UI_TAKE, 
        SPRITE_UI_TALK, 
        SPRITE_UI_OBSERVE, 
        SPRITE_UI_MOUSE_MOVE, 
        SPRITE_UI_CURSOR_DOOR, 
        BACKGROUND_HIVE1_ROOM1, 
        SPRITE_ITEM_CHEST_CLOSED, 
        SPRITE_ITEM_CHEST_OPENED, 
        SPRITE_ITEM_CARDS, 
        SPRITE_ITEM_CARDS_PICKABLE, 
        SPRITE_ITEM_DECO_BED_LAYER, 
        SPRITE_ITEM_WARDROBE_OPENED, 
        BACKGROUND_HIVE1_CORRIDOR1, 
        SPRITE_NPC_REME_IDLE, 
        BACKGROUND_HIVE1_HALL1, 
        BACKGROUND_HIVE1_WC, 
        SPRITE_MEMENTO_JOB, 
        SPRITE_PICKABLE_SOAP, 
        BACKGROUND_HIVE1_CORRIDOR1_N, 
        BACKGROUND_HIVE1_HALL1_N, 
        BACKGROUND_HIVE1_WC_N, 
        BACKGROUND_CITY1_STREET1, 
        BACKGROUND_CITY1_STREET1_N, 
        BACKGROUND_CITY1_STREET2, 
        BACKGROUND_CITY1_STREET2_N, 
        BACKGROUND_PHARMACY1, 
        SPRITE_NPC_PHARMACY_QUEUE, 
        SPRITE_NPC_PHARMACY_OWNER, 
        BACKGROUND_CITY1_MANYO, 
        BACKGROUND_CITY1_MANYO_NIGHT, 
        SPRITE_CITY1_MANYO_UMBRELLA, 
        SPRITE_PICKABLE_UMBRELLA, 
        SPRITE_MANYO_OWNER, 
        SPRITE_MEMENTO_RECIPE, 
        SPRITE_HIVE1_POOR_MAN_STEADY, 
        SPRITE_MEMENTO_POOR_MAN_WC, 
        SPRITE_HIVE1_ROACH_HEAD, 
        BACKGROUND_BACKALLEY, 
        BACKGROUND_BACKALLEY_NIGHT, 
        SPRITE_HIVE1_SHOELACE, 
        SPRITE_SHOELACE_PICKABLE, 
        SPRITE_HIVE1_VALVE_BOX_OPENED, 
        SPRITE_LAST, 
        
        SPRITE_TOTAL
        /* > ATG 1 END < */
    }
}
