using UnityEngine;

namespace Gob3AQ.VARMAP.Types
{
    public enum GameItem
    {
        /* > ATG 1 START < */
        ITEM_NONE = -1, 
        ITEM_PLAYER_MAIN, 
        ITEM_PLAYER_PARROT, 
        ITEM_PLAYER_SNAKE, 
        ITEM_VICTIM, 
        ITEM_WITNESS1, 
        ITEM_WITNESS2, 
        ITEM_WITNESS3, 
        ITEM_ROOM1_DOOR_KITCHEN, 
        ITEM_ROOM1_DOOR_MAIN, 
        ITEM_DOOR_UNCONDITIONAL, 
        ITEM_ROOM1_SPOON, 
        ITEM_ROOM1_DRAWER, 
        ITEM_ROOM1_WINDOW, 
        ITEM_ROOM1_POISON_REMAIN, 
        ITEM_ROOM1_SPOON_W_POIS, 
        ITEM_ROOM1_OLD_KEY, 
        ITEM_ROOM1_TROWEL, 
        ITEM_ROOM1_WINDOW_OP_1, 
        ITEM_ROOM1_WINDOW_OP_2, 
        ITEM_DOOR_UNCONDITIONAL_2, 
        ITEM_ROOM1_VALVE, 
        ITEM_ROOM1_FOUNTAIN, 
        ITEM_ROOM1_DOG, 
        ITEM_ROOM1_CAR, 
        ITEM_ROOM1_CAR_DOOR_CLOSED, 
        ITEM_ROOM1_CAR_KEYHOLE, 
        ITEM_DOOR_UNCONDITIONAL_3, 
        ITEM_ROOM1_MATCHES, 
        ITEM_ROOM1_WINDOW_AS_DOOR, 
        ITEM_ROOM1_CAR_DOOR_AS_DOOR, 
        ITEM_ROOM1_DARKNESS, 
        ITEM_ROOM1_CANDLE, 
        ITEM_ROOM1_LOCKPICK, 
        ITEM_ROOM1_OIL_BOTTLES, 
        ITEM_LAST, 
        
        ITEM_TOTAL
        /* > ATG 1 END < */
    }

    public enum GamePickableItem
    {
        /* > ATG 2 START < */
        ITEM_PICK_NONE = -1,
        ITEM_PICK_ROOM1_SPOON, 
        ITEM_PICK_ROOM1_SPOON_W_POIS, 
        ITEM_PICK_ROOM1_OLD_KEY, 
        ITEM_PICK_ROOM1_TROWEL, 
        ITEM_PICK_ROOM1_MATCHES, 
        ITEM_PICK_ROOM1_LOCKPICK, 
        
        ITEM_PICK_TOTAL
        /* > ATG 2 END < */
    }

    public enum ActionConditions
    {
        /* > ATG 3 START < */
        COND_OK, 
        COND_ROOM1_OBSERVE_VICTIM, 
        COND_ROOM1_TALK_WITNESS1, 
        COND_ROOM1_TALK_WITNESS2, 
        COND_ROOM1_NOT_CROSS_DOOR, 
        COND_ROOM1_NOT_CROSS_MAIN_DOOR, 
        COND_ROOM1_TAKE_SPOON, 
        COND_ROOM1_USE_SPOON_POIS_WITN, 
        COND_ROOM1_TALK_WITNESS3, 
        COND_ROOM1_USE_SPOON_W_JAM, 
        COND_ROOM1_USE_KEY_WINDOW, 
        COND_ROOM1_TAKE_TROWEL, 
        COND_ROOM1_TAKE_CAR_DOOR, 
        COND_ROOM1_USE_KEY_CAR, 
        COND_ROOM1_TAKE_MATCHES, 
        COND_ROOM1_TAKE_DARKNESS, 
        COND_ROOM1_USE_MATCHES, 
        COND_ROOM1_TAKE_LOCKPICK, 
        COND_LAST, 
        
        COND_TOTAL
        /* > ATG 3 END < */
    }

    public enum UnchainConditions
    {
        /* > ATG 4 START < */
        UNCHAIN_ROOM1_INITIAL_MEMENTO, 
        UNCHAIN_ROOM1_INITIAL_EVENT, 
        UNCHAIN_ROOM1_OBSERVE_VICTIM, 
        UNCHAIN_ROOM1_MEMENTO_CHASE_0, 
        UNCHAIN_ROOM1_MEMENTO_CHASE_0_bis, 
        UNCHAIN_ROOM1_NEED_FLEE, 
        UNCHAIN_ROOM1_MEMENTO_CHASE_1, 
        UNCHAIN_ROOM1_TAKE_SPOON_1, 
        UNCHAIN_ROOM1_TAKE_SPOON_2, 
        UNCHAIN_ROOM1_TAKE_SPOON_POIS_1, 
        UNCHAIN_ROOM1_TAKE_SPOON_POIS_2, 
        UNCHAIN_ROOM1_TAKE_SPOON_POIS_3, 
        UNCHAIN_ROOM1_TAKE_OLD_KEY, 
        UNCHAIN_ROOM1_WINDOW_OPENED_1, 
        UNCHAIN_ROOM1_WINDOW_OPENED_2, 
        UNCHAIN_ROOM1_WINDOW_OPENED_3, 
        UNCHAIN_ROOM1_WINDOW_OPENED_4, 
        UNCHAIN_ROOM1_WINDOW_OPENED_5, 
        UNCHAIN_ROOM1_TAKE_TROWEL_1, 
        UNCHAIN_ROOM1_TAKE_TROWEL_2, 
        UNCHAIN_ROOM1_OPEN_CAR_DOOR_1, 
        UNCHAIN_ROOM1_OPEN_CAR_DOOR_2, 
        UNCHAIN_ROOM1_OPEN_CAR_DOOR_3, 
        UNCHAIN_ROOM1_TAKE_MATCHES_1, 
        UNCHAIN_ROOM1_TAKE_MATCHES_2, 
        UNCHAIN_ROOM1_FIRE_CANDLE, 
        UNCHAIN_ROOM1_FIRE_CANDLE_2, 
        UNCHAIN_ROOM1_TAKE_LOCKPICK_1, 
        UNCHAIN_ROOM1_TAKE_LOCKPICK_2, 
        
        UNCHAIN_TOTAL
        /* > ATG 4 END < */
    }
}
