using UnityEngine;

namespace Gob3AQ.VARMAP.Types
{
    public enum DialogType
    {
        /* > ATG 1 START < */
        DIALOG_NONE = -1, 
        DIALOG_SIMPLE, 
        DIALOG_WITNESS1, 
        DIALOG_WITNESS2, 
        DIALOG_WITNESS3_PROLOGUE, 
        DIALOG_WITNESS3_MAIN, 
        DIALOG_WITNESS3_SPOON, 
        DIALOG_LAST, 
        
        DIALOG_TOTAL
        /* > ATG 1 END < */
    }

    public enum DialogOption
    {
        /* > ATG 2 START < */
        DIALOG_OPTION_NONE = -1, 
        DIALOG_OPTION_SIMPLE, 
        DIALOG_OPTION_WITNESS1_INNOCENT, 
        DIALOG_OPTION_WITNESS2_GUARDS, 
        DIALOG_OPTION_WITNESS3_PROLO, 
        DIALOG_OPTION_WITNESS3_MAIN_1, 
        DIALOG_OPTION_WITNESS3_MAIN_2, 
        DIALOG_OPTION_WITNESS3_SPOON, 
        DIALOG_OPTION_WITNESS3_SPOON_2, 
        DIALOG_OPTION_LAST, 
        
        DIALOG_OPTION_TOTAL
        /* > ATG 2 END < */
    }

    public enum DialogPhrase
    {
        /* > ATG 3 START < */
        PHRASE_NONE = -1, 
        PHRASE_NONSENSE, 
        PHRASE_NONSENSE_OBSERVE, 
        PHRASE_NONSENSE_TALK, 
        PHRASE_NONSENSE_NOT_THOUGHT, 
        PHRASE_NONSENSE_COMBI, 
        PHRASE_ALREADY_COMBI, 
        PHRASE_GREAT_IDEA_COMBI, 
        PHRASE_MEMENTO_VICTIM_CASE_0, 
        PHRASE_MEMENTO_VICTIM_CASE_1, 
        PHRASE_ROOM1_OBSERVE_VICTIM, 
        PHRASE_ROOM1_WITNESS1_INNOCENT0, 
        PHRASE_ROOM1_WITNESS1_INNOCENT1, 
        PHRASE_ROOM1_WITNESS1_INNOCENT2, 
        PHRASE_ROOM1_WITNESS1_INNOCENT3, 
        PHRASE_ROOM1_WITNESS2_GUARDS0, 
        PHRASE_ROOM1_WITNESS2_GUARDS1, 
        PHRASE_MEMENTO_CHASE_0, 
        PHRASE_MEMENTO_CHASE_1, 
        PHRASE_ROOM1_NOT_CROSS_DOOR, 
        PHRASE_ROOM1_NOT_CROSS_MAIN_DOOR, 
        PHRASE_ROOM1_TAKE_SPOON, 
        PHRASE_ROOM1_WITNESS3_PROLO, 
        PHRASE_ROOM1_WITNESS3_MAIN_1_1, 
        PHRASE_ROOM1_WITNESS3_MAIN_1_2, 
        PHRASE_ROOM1_WITNESS3_MAIN_2_1, 
        PHRASE_ROOM1_WITNESS3_MAIN_2_2, 
        PHRASE_ROOM1_WITNESS3_SPOON_1, 
        PHRASE_ROOM1_WITNESS3_SPOON_2, 
        PHRASE_ROOM1_WITNESS3_SPOON_3, 
        PHRASE_ROOM1_WITNESS3_SPOON_4, 
        PHRASE_ROOM1_WITNESS3_SPOON_5, 
        PHRASE_ROOM1_TAKE_SPOON_POISON, 
        PHRASE_ROOM1_WITNESS3_SPOON_2_1, 
        PHRASE_ROOM1_USE_KEY_WINDOW, 
        PHRASE_ROOM1_TAKE_TROWEL, 
        
        PHRASE_TOTAL
        /* > ATG 3 END < */
    }

    public enum DialogLanguages
    {
        DIALOG_LANG_ENGLISH = 0,
        DIALOG_LANG_SPANISH,
        DIALOG_LANG_FRENCH,
        DIALOG_LANG_GERMAN,
        DIALOG_LANG_ITALIAN,
        DIALOG_LANG_PORTUGUESE,
        
        DIALOG_LANG_TOTAL
    }
}
