namespace Gob3AQ.VARMAP.Enum
{
    public enum VARMAP_Variable_ID
    {
        /* > ATG 1 START < */
        VARMAP_ID_NONE,
        VARMAP_ID_GAME_OPTIONS,
        VARMAP_ID_ELAPSED_TIME_MS,
        VARMAP_ID_ACTUAL_ROOM,
        VARMAP_ID_ITEMS_COLLECTED,
        VARMAP_ID_EVENTS_OCCURRED,
        VARMAP_ID_GAMESTATUS,
        VARMAP_ID_PRESSED_KEYS,
        VARMAP_ID_MOUSE_PROPERTIES,
        VARMAP_ID_PLAYER_POSITION,
        VARMAP_ID_PLAYER_ID_SELECTED,
        VARMAP_ID_TOTAL
        /* > ATG 1 END < */
    }

    
}
